config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  devise_for          :users

  resources           :venues do
    resources           :events do
      resources           :tickets, only: [:index, :show]
      resources           :ticket_options
    end
  end
end

app/models/ticket_option.rb
class TicketOption < ApplicationRecord
  belongs_to :event

  validates :price, presence: true
  validates :limit, presence: true
  validates :name, presence: true
  validates :expiration, presence: true
end

app/controllers/ticket_options_controller.rb
class TicketOptionsController < ApplicationController
  before_action :set_event, only: [:index, :new, :create]
  before_action :set_ticket_option, only: [:show, :edit, :update, :destroy]
  before_action :set_venue, except: :index
  after_action :venue_authorization, except: :index

  def index
    @ticket_options = @event.ticket_options
  end

  def show
  end

  def new
    @ticket_option = @event.ticket_options.build
  end

  def edit
  end

  def create
    @ticket_option = @event.ticket_options.build(ticket_option_params)
    if @ticket_option.save
      redirect_to @ticket_option, notice: 'Ticket option was successfully created.'
    else
      render :new
    end
  end

  def update
    if @ticket_option.update(ticket_option_params)
      redirect_to @ticket_option, notice: 'Ticket option was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ticket_option.destroy
    redirect_to ticket_options_url, notice: 'Ticket option was successfully destroyed.'
  end

  private
    def set_ticket_option
      @ticket_option = TicketOption.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    def set_venue
      @venue = Venue.find(params[:venue_id])
    end

    def ticket_option_params
      params.require(:ticket_option).permit(:name, :description, :price, :expiration, :limit)
    end
end

app/helpers/ticket_options_helper.rb
module TicketOptionsHelper
end

app/views/ticket_options/_form.html.erb
<%= form_with(model: [@venue, @event, ticket_option], local: true) do |form| %>
  <% if ticket_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket_option.errors.count, "error") %> prohibited this ticket_option from being saved:</h2>

      <ul>
      <% ticket_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: 1 %>
  </div>

  <div class="field">
    <%= form.label :limit %>
    <%= form.number_field :limit, step: 1 %>
  </div>

  <div class="field">
    <%= form.label :expiration %>
    <%= form.datetime_field :expiration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ticket_options/edit.html.erb
<%= render 'form', ticket_option: @ticket_option %>

app/views/ticket_options/index.html.erb
<% @ticket_options.each do |option| %>
  <ul>
    <li><%= option.name %></li>
    <li><%= option.description %></li>
    <li><%= number_to_currency(option.price/100) %></li>
    <li><%= option.limit %></li>
    <li><%= option.expiration %></li>
  </ul>
<% end %>

<%= link_to "New Tickets", new_venue_event_ticket_option_path(@event.venue, @event) %>

app/views/ticket_options/new.html.erb
<%= render 'form', ticket_option: @ticket_option %>