config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  devise_for          :users

  resources           :venues do
    resources           :events do
      resources           :tickets, only: [:index, :show]
      resources           :ticket_options
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  has_many :ticket_options, dependent: :destroy
  has_many :tickets, through: :ticket_options

  validates :venue_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :name, presence: true
  validate :valid_time

  def valid_time
    if end_time <= start_time || end_time <= Time.now
      errors.add(:base, "The time for you event isn't valid.")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_venue, exclude: :show
  after_action :venue_authorization, except: [:index, :show]
  skip_before_action :user_authorized?, only: [:index, :show]


  def index
    @events = @venue.events
  end

  def show
    @ticket_options = @event.ticket_options.all
  end

  def new
    @event = @venue.events.build
  end

  def edit
  end

  def create
    @event = @venue.events.build(event_params)
    if @event.save
      redirect_to venue_event_path(@venue, @event), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to venue_event_path(@venue, @event), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to venue_events_path(@venue), notice: 'Event was successfully destroyed.'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def set_venue
      @venue = Venue.find(params[:venue_id])
    end

    def event_params
      params.require(:event).permit(:start_time, :end_time, :name, :description, :venue_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: [@venue, event], local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_field :end_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', venue_event_path(@event) %> |
<%= link_to 'Back', venue_events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
  <ul>
    <h4><%= event.name %></h4>
    <ul>
      :start_time, :end_time, :name, :description, :venue_id
      <li><%= event.name %></li>
      <li><%= event.description %></li>
      <li><%= event.start_time %></li>
      <li><%= event.end_time %></li>
    </ul>
    <%= link_to 'Show', venue_event_path(@venue, event) %>
    <% if current_user %>
      <% if policy(event).update? %>
        <%= link_to 'Edit', edit_venue_event_path(@venue, event) %>
      <% end %>
      <% if policy(event).destroy? %>
        <%= link_to 'Destroy', venue_event_path(@venue, event),
                               method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
  </ul>

  <br>
  <br>

<% end %>

<br>
<br>

<%= link_to 'New Event', new_venue_event_path(@venue) %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', venue_events_path(@venue) %>

app/views/events/show.html.erb
<ul>
  <li><%= @event.name %></li>
  <li><%= @event.description %></li>
  <li><%= @event.start_time %></li>
  <li><%= @event.end_time %></li>
</ul>

<% @ticket_options.each do |option| %>
  <ul>
    <li><%= option.name %></li>
    <li><%= option.description %></li>
    <li><%= number_to_currency(option.price/100) %></li>
    <li><%= option.limit %></li>
    <li><%= option.expiration %></li>
  </ul>
<% end %>

<% if current_user && policy(@event).update? %>
  <%= link_to 'Edit', edit_venue_event_path(@venue, @event) %> |
<% end %>
<%= link_to 'Back', venue_events_path(@venue) %>

<div>
  <%= link_to "Ticket Options", venue_event_ticket_options_path(@event.venue, @event) %>
</div>