config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  devise_for          :users

  resources           :venues do
    resources           :events do
      resources           :tickets, only: [:index, :show]
      resources           :ticket_options
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: :show
  before_action :set_event, only: :index
  before_action :set_venue
  after_action :venue_authorization

  def index
    @tickets = @event.tickets.all
  end

  def show
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def set_event
      @event = Event.find([:event_id])
    end

    def set_venue
      @venue = Venue.find(params[:venue_id])
    end

    def ticket_params
      params.require().permit()
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>