config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  devise_for          :users

  resources           :venues do
    resources           :events do
      resources           :tickets, only: [:index, :show]
      resources           :ticket_options
    end
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  resourcify

  has_many :events, dependent: :destroy

  validates :name, presence: :true
  validates :location, presence: :true
  validates :age, presence: :true
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  after_action :venue_authorization, only: [:new, :edit, :create, :update, :destroy]
  skip_before_action :user_authorized?, only: [:index, :show]

  def index
    @venues = Venue.all
  end

  def show
    @events = @venue.events.last(3)
  end

  def new
    @venue = Venue.new
  end

  def edit
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to @venue, notice: 'Venue was successfully created.'
    else
      render :new
    end
  end

  def update
    if @venue.update(venue_params)
      redirect_to @venue, notice: 'Venue was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    redirect_to venues_url, notice: 'Venue was successfully destroyed.'
  end

  private
    def set_venue
      @venue = Venue.find(params[:id])
    end

    def venue_params
      params.require(:venue).permit(:name, :location, :age, :email, :phone, :capacity,
                                    :music, :dress_code, :website, :category)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_with(model: venue, local: true) do |form| %>
  <% if venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :music %>
    <%= form.text_field :music %>
  </div>

  <div class="field">
    <%= form.label :dress_code %>
    <%= form.text_field :dress_code %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Venues</h1>
<% @venues.each do |venue| %>
  <ul>
    <h4><%= venue.name %></h4>
    <ul>
      <li><%= venue.location %></li>
      <li><%= venue.age %></li>
      <li><%= venue.email %></li>
      <li><%= venue.phone %></li>
      <li><%= venue.capacity %></li>
      <li><%= venue.music %></li>
      <li><%= venue.dress_code %></li>
      <li><%= venue.category %></li>
      <li><%= venue.website %></li>
    </ul>

    <%= link_to 'Show', venue %>
    <% if current_user %>
      <% if policy(venue).update? %>
        <%= link_to 'Edit', edit_venue_path(venue) %>
      <% end %>
      <% if policy(venue).destroy? %>
        <%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
  </ul>

  <br>
  <br>

<% end %>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<h4><%= @venue.name %></h4>
<ul>
  <li><%= @venue.location %></li>
  <li><%= @venue.age %></li>
  <li><%= @venue.email %></li>
  <li><%= @venue.phone %></li>
  <li><%= @venue.capacity %></li>
  <li><%= @venue.music %></li>
  <li><%= @venue.dress_code %></li>
  <li><%= @venue.category %></li>
  <li><%= @venue.website %></li>
</ul>


<% @events.each do |event| %>
  <%= link_to venue_event_path(@venue, event) do %>
    <h4><%= event.name %></h4>
  <% end %>
  <ul>
    <li><%= event.name %></li>
    <li><%= event.description %></li>
    <li><%= event.start_time %></li>
    <li><%= event.end_time %></li>
  </ul>
<% end %>

<div>
  <%= link_to "Events", venue_events_path(@venue) %>
  <% if current_user && policy(@venue).update? %>
    <%= link_to 'Edit', edit_venue_path(@venue) %> |
  <% end %>
  <%= link_to 'Back', venues_path %>
</div>